# Generated by Django 5.1.7 on 2025-05-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Subir imagen cuadrada de 500x500px para mejor calidad",
                null=True,
                upload_to="productos/",
            ),
        ),
    ]
