# Generated by Django 5.1.7 on 2025-05-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areapreparacion",
            name="nombre",
            field=models.CharField(
                choices=[("cocina", "Cocina"), ("bar", "Bar"), ("barra", "Barra")],
                max_length=50,
                unique=True,
            ),
        ),
    ]
