# Generated by Django 5.1.7 on 2025-07-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_movimientostock_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="costo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Costo del producto",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio de venta del producto",
                max_digits=10,
            ),
        ),
    ]
