"""
Django settings for cafeteria project.

Generated by 'django-admin startproject' using Django 5.1.7.
Optimizado para Xprinter XP-A160H y acceso móvil.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ===============================
# CONFIGURACIÓN BÁSICA DE DJANGO
# ===============================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-yv1a-#q#0*n@@_5j3=94&@$r(&s&$wfuf7#q)i+fv+qfi6@ht3"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Hosts permitidos - expandido para acceso móvil
ALLOWED_HOSTS = [
    "10.201.71.215",
    "127.0.0.1",
    "localhost",
    "192.168.1.*",      # Red típica doméstica/oficina
    "192.168.0.*",      # Red alternativa común
    "10.0.0.*",         # Red de oficina
    "172.16.*",         # Red privada
    # Agregar IPs específicas según necesidades
]

# ===============================
# CONFIGURACIÓN DE AUTENTICACIÓN
# ===============================

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Configuración de sesiones optimizada para móviles
SESSION_COOKIE_AGE = 86400          # 24 horas (aumentado para móviles)
SESSION_SAVE_EVERY_REQUEST = False  # Mejorado para rendimiento
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Permitir sesiones persistentes
SESSION_COOKIE_SECURE = False       # False para HTTP (desarrollo)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'users.Usuario'

# ===============================
# CONFIGURACIÓN CORS PARA MÓVILES
# ===============================

CORS_ALLOW_ALL_ORIGINS = True  # ⚠️ Solo para desarrollo/red privada
CORS_ALLOWED_ORIGINS = [
    "http://10.201.71.215:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    # Agregar más IPs según necesidades
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CSRF_TRUSTED_ORIGINS = [
    f'http://{host}:8000' for host in ["10.201.71.215", "localhost", "127.0.0.1"]
]

# ===============================
# APLICACIONES INSTALADAS
# ===============================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    
    # Apps del proyecto
    "users",
    "products",
    "orders",
    "notifications",
    "audit",
    "compras",
    
    # Librerías externas
    "crispy_forms",
    "crispy_bootstrap5",
    "corsheaders",  # Para CORS
]

# ===============================
# MIDDLEWARE
# ===============================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS para móviles
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "audit.middleware.AuditMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware", 
    "users.middleware.SessionTimeoutMiddleware",
]

ROOT_URLCONF = "cafeteria.urls"

# ===============================
# CONFIGURACIÓN DE TEMPLATES
# ===============================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = 'bootstrap5'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["C:/wamp64/www/python/cafeteria/cafeteria/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "cafeteria.wsgi.application"

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS
# ===============================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cafeteria1_db',
        'USER': 'jortega',
        'PASSWORD': 'Carlos.2024',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# ===============================
# VALIDACIÓN DE CONTRASEÑAS
# ===============================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ===============================
# INTERNACIONALIZACIÓN
# ===============================

LANGUAGE_CODE = "es-cl"
TIME_ZONE = "America/Santiago"
USE_I18N = True
USE_TZ = True

# ===============================
# ARCHIVOS ESTÁTICOS Y MEDIA
# ===============================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ===============================
# CONFIGURACIÓN ESPECÍFICA XPRINTER XP-A160H
# ===============================

# IP de la impresora Xprinter XP-A160H (⚠️ CAMBIAR POR TU IP REAL)
PRINTER_IP = '10.201.71.207'  # ⚠️ CAMBIAR POR TU IP REAL
PRINTER_PORT = 9100
PRINTER_TIMEOUT = 15

# Configuración completa para XP-A160H
XPRINTER_CONFIG = {
    'model': 'XP-A160H',
    'manufacturer': 'Xprinter',
    
    # Especificaciones técnicas
    'paper_width_mm': 80,
    'paper_width_tolerance': 0.5,
    'print_speed_mm_s': 160,
    'chars_per_line': 32,
    'dpi': 203,
    
    # Configuración de papel
    'paper_types': ['thermal_80mm'],
    'auto_cut': True,
    'partial_cut_preferred': True,
    
    # Configuración de caracteres
    'encoding': 'utf-8',
    'fallback_encoding': 'latin-1',
    'char_set': 0,
    'code_page': 0,
    
    # Comandos ESC/POS específicos
    'commands': {
        'init': '\x1b@',
        'reset': '\x1bc\x00',
        'bold_on': '\x1bE\x01',
        'bold_off': '\x1bE\x00',
        'double_height': '\x1b!\x10',
        'double_width': '\x1b!\x20',
        'double_size': '\x1b!\x30',
        'normal_size': '\x1b!\x00',
        'center': '\x1ba\x01',
        'left': '\x1ba\x00',
        'right': '\x1ba\x02',
        'full_cut': '\x1dVA\x00',
        'partial_cut': '\x1dVB\x00',
        'feed_lines': lambda n: f'\x1bd{chr(n)}',
    },
    
    # Configuración de red
    'network': {
        'protocol': 'raw',
        'port': 9100,
        'chunk_size': 1024,
        'chunk_delay': 0.01,
        'max_retries': 3,
        'retry_delay': 1,
    },
    
    # Compatibilidad
    'os_compatibility': [
        'Windows 2000', 'Windows 2003', 'Windows XP',
        'Windows Vista', 'Windows 7', 'Windows 8', 
        'Windows 10', 'Windows 11', 'Linux'
    ],
    'driver_required': False,
    'escpos_compatible': True,
}

# ===============================
# CONFIGURACIÓN DE CACHE
# ===============================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'xprinter-cache',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

PRINTER_CACHE_TIMEOUT = 60

# ===============================
# CONFIGURACIÓN DE DETECCIÓN AUTOMÁTICA
# ===============================

PRINTER_AUTO_DETECT = {
    'enabled': True,
    'scan_networks': [
        '192.168.1.0/24',
        '192.168.0.0/24',
        '10.0.0.0/24',
        '10.201.71.0/24',  # Tu red actual
    ],
    'scan_timeout': 1,
    'cache_detection': 300,
}

# ===============================
# CONFIGURACIÓN DE LOGGING OPTIMIZADA
# ===============================

# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "auth_debug.log",
            'formatter': 'verbose',
        },
        'printer_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'xprinter_a160h.log',
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    "loggers": {
        "django.security": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "django.db.backends": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "django.auth": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
        'printer': {
            'handlers': ['printer_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'xprinter': {
            'handlers': ['printer_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ===============================
# CONFIGURACIÓN PWA OPCIONAL
# ===============================

PWA_CONFIG = {
    'name': 'Sistema Cafetería - Xprinter XP-A160H',
    'short_name': 'Cafetería XP-A160H',
    'description': 'Sistema de gestión de cafetería con impresión directa',
    'theme_color': '#667eea',
    'background_color': '#ffffff',
    'display': 'standalone',
    'start_url': '/dashboard/',
    'icons': [
        {
            'src': '/static/icons/icon-192x192.png',
            'sizes': '192x192',
            'type': 'image/png'
        }
    ]
}

# ===============================
# CONFIGURACIONES DE SEGURIDAD
# ===============================

# Configuraciones específicas para desarrollo
if DEBUG:
    # Configuración para desarrollo
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
else:
    # Configuraciones de seguridad para producción
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ===============================
# INSTRUCCIONES DE INSTALACIÓN
# ===============================

"""
COMANDOS PARA INSTALAR DEPENDENCIAS REQUERIDAS:

pip install django-cors-headers

CONFIGURACIÓN INICIAL:

1. Cambiar PRINTER_IP por la IP real de tu impresora XP-A160H
2. Verificar que la impresora esté en la misma red
3. Ejecutar: python manage.py collectstatic
4. Crear directorio de logs: mkdir logs (se crea automáticamente)

VERIFICAR IP DE LA IMPRESORA:

1. Imprime una página de configuración desde la impresora
2. O desde el panel de la impresora: Configuración > Red > Información
3. También puedes usar herramientas de red como nmap o arp-scan

PRUEBA DE CONECTIVIDAD:

ping [IP_DE_LA_IMPRESORA]
telnet [IP_DE_LA_IMPRESORA] 9100

ACCESO MÓVIL:

1. Asegúrate de que tu dispositivo móvil esté en la misma red WiFi
2. Usa la IP del servidor: http://[IP_DEL_SERVIDOR]:8000
3. Ejemplo: http://10.201.71.215:8000

PARA PRODUCCIÓN:

1. Cambiar DEBUG = False
2. Configurar SECRET_KEY desde variable de entorno
3. Usar HTTPS y configurar certificados SSL
4. Configurar firewall para permitir solo IPs necesarias
5. Usar base de datos en servidor dedicado
"""