"""
Django settings for cafeteria project.

Generated by 'django-admin startproject' using Django 5.1.7.
Optimizado para Xprinter XP-A160H y acceso móvil.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ===============================
# CONFIGURACIÓN BÁSICA DE DJANGO
# ===============================

SECRET_KEY = os.environ.get('SECRET_KEY')

DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ✅ CORRECCIÓN: Django NO soporta wildcards (*) en ALLOWED_HOSTS
# Se deben poner las IPs exactas. Agregada tu IP 192.168.0.139
ALLOWED_HOSTS = [
    "192.168.0.139",    # ✅ Tu IP de producción (AGREGADA)
    "10.201.71.215",    # IP anterior del servidor
    "127.0.0.1",
    "localhost",
    # ⚠️ Agrega aquí cualquier otra IP exacta que necesites
    # Los wildcards como "192.168.1.*" NO FUNCIONAN en Django
]

# ===============================
# CONFIGURACIÓN DE AUTENTICACIÓN
# ===============================

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ✅ CORRECCIÓN: SESSION_SAVE_EVERY_REQUEST=True es importante en móviles
# para que la sesión no expire inesperadamente entre peticiones
SESSION_COOKIE_AGE = 86400              # 24 horas
SESSION_SAVE_EVERY_REQUEST = True       # ✅ CORREGIDO (era False, causaba cuelgues)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False # Sesiones persistentes en móvil
SESSION_COOKIE_SECURE = False           # False para HTTP local
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

AUTH_USER_MODEL = 'users.Usuario'

# ===============================
# CONFIGURACIÓN CORS PARA MÓVILES
# ===============================

CORS_ALLOW_ALL_ORIGINS = True  # OK para red privada/desarrollo

# ✅ CORRECCIÓN: Agregada tu IP 192.168.0.139 en todos los orígenes
CORS_ALLOWED_ORIGINS = [
    "http://192.168.0.139:8000",    # ✅ Tu IP de producción (AGREGADA)
    "http://10.201.71.215:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ✅ CORRECCIÓN: Agregada tu IP 192.168.0.139 en CSRF_TRUSTED_ORIGINS
# Sin esto, cualquier POST desde el celular falla con error 403 (Forbidden)
CSRF_TRUSTED_ORIGINS = [
    "http://192.168.0.139:8000",    # ✅ Tu IP de producción (AGREGADA)
    "http://10.201.71.215:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# ===============================
# APLICACIONES INSTALADAS
# ===============================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    
    # Apps del proyecto
    "users",
    "products",
    "orders",
    "notifications",
    "audit",
    "compras",
    
    # Librerías externas
    "crispy_forms",
    "crispy_bootstrap5",
    "corsheaders",
]

# ===============================
# MIDDLEWARE
# ===============================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "audit.middleware.AuditMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "users.middleware.SessionTimeoutMiddleware",
]

ROOT_URLCONF = "cafeteria.urls"

# ===============================
# CONFIGURACIÓN DE TEMPLATES
# ===============================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = 'bootstrap5'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["C:/wamp64/www/python/cafeteria/cafeteria/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "cafeteria.wsgi.application"

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS
# ===============================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': 300,
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}

# ===============================
# VALIDACIÓN DE CONTRASEÑAS
# ===============================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ===============================
# INTERNACIONALIZACIÓN
# ===============================

LANGUAGE_CODE = "es-cl"
TIME_ZONE = "America/Santiago"
USE_I18N = True
USE_TZ = True

# ===============================
# ARCHIVOS ESTÁTICOS Y MEDIA
# ===============================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ===============================
# CONFIGURACIÓN ESPECÍFICA XPRINTER SPRT-80mm
# ===============================

PRINTER_IP = '10.201.71.207'
PRINTER_PORT = 9100
PRINTER_TIMEOUT = 15

XPRINTER_CONFIG = {
    'model': 'SPRT-80mm',
    'manufacturer': 'Xprinter',
    'paper_width_mm': 80,
    'paper_width_tolerance': 0.5,
    'print_speed_mm_s': 160,
    'chars_per_line': 32,
    'dpi': 203,
    'paper_types': ['thermal_80mm'],
    'auto_cut': True,
    'partial_cut_preferred': True,
    'encoding': 'utf-8',
    'fallback_encoding': 'latin-1',
    'char_set': 0,
    'code_page': 0,
    'commands': {
        'init': '\x1b@',
        'reset': '\x1bc\x00',
        'bold_on': '\x1bE\x01',
        'bold_off': '\x1bE\x00',
        'double_height': '\x1b!\x10',
        'double_width': '\x1b!\x20',
        'double_size': '\x1b!\x30',
        'normal_size': '\x1b!\x00',
        'center': '\x1ba\x01',
        'left': '\x1ba\x00',
        'right': '\x1ba\x02',
        'full_cut': '\x1dVA\x00',
        'partial_cut': '\x1dVB\x00',
        'feed_lines': lambda n: f'\x1bd{chr(n)}',
    },
    'network': {
        'protocol': 'raw',
        'port': 9100,
        'chunk_size': 1024,
        'chunk_delay': 0.01,
        'max_retries': 3,
        'retry_delay': 1,
    },
    'os_compatibility': [
        'Windows 2000', 'Windows 2003', 'Windows XP',
        'Windows Vista', 'Windows 7', 'Windows 8',
        'Windows 10', 'Windows 11', 'Linux'
    ],
    'driver_required': False,
    'escpos_compatible': True,
}

# ===============================
# CONFIGURACIÓN DE CACHE
# ===============================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'xprinter-cache',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

PRINTER_CACHE_TIMEOUT = 60

# ===============================
# CONFIGURACIÓN DE DETECCIÓN AUTOMÁTICA
# ===============================

PRINTER_AUTO_DETECT = {
    'enabled': True,
    'scan_networks': [
        '192.168.1.0/24',
        '192.168.0.0/24',
        '10.0.0.0/24',
        '10.201.71.0/24',
    ],
    'scan_timeout': 1,
    'cache_detection': 300,
}

# ===============================
# ✅ CORRECCIÓN: LOGGING OPTIMIZADO
# El logging original tenía django.db.backends en DEBUG, lo que
# registra CADA consulta SQL y enlentece enormemente la app en móviles
# ===============================

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    "handlers": {
        "file": {
            "level": "WARNING",         # ✅ CORREGIDO: era DEBUG, ahora WARNING
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "auth_debug.log",
            'formatter': 'verbose',
        },
        'printer_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'xprinter_a160h.log',
            'maxBytes': 1024*1024*5,    # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'WARNING',         # ✅ CORREGIDO: era DEBUG, ahora WARNING
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    "loggers": {
        "django.security": {
            "handlers": ["file"],
            "level": "WARNING",         # ✅ CORREGIDO: era DEBUG
            "propagate": True,
        },
        # ✅ ELIMINADO: django.db.backends en DEBUG registra cada SQL
        # y es una de las principales causas de lentitud en móviles
        "django.auth": {
            "handlers": ["file"],
            "level": "WARNING",         # ✅ CORREGIDO: era DEBUG
            "propagate": True,
        },
        'printer': {
            'handlers': ['printer_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'xprinter': {
            'handlers': ['printer_file', 'console'],
            'level': 'INFO',            # ✅ CORREGIDO: era DEBUG
            'propagate': False,
        },
    },
}

# ===============================
# CONFIGURACIÓN PWA OPCIONAL
# ===============================

PWA_CONFIG = {
    'name': 'Sistema Cafetería - Xprinter XP-A160H',
    'short_name': 'Cafetería XP-A160H',
    'description': 'Sistema de gestión de cafetería con impresión directa',
    'theme_color': '#667eea',
    'background_color': '#ffffff',
    'display': 'standalone',
    'start_url': '/dashboard/',
    'icons': [
        {
            'src': '/static/icons/icon-192x192.png',
            'sizes': '192x192',
            'type': 'image/png'
        }
    ]
}

# ===============================
# CONFIGURACIONES DE SEGURIDAD
# ===============================

if DEBUG:
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
else:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ===============================
# INSTRUCCIONES DE INSTALACIÓN
# ===============================

"""
COMANDOS PARA INSTALAR DEPENDENCIAS REQUERIDAS:

pip install django-cors-headers

CONFIGURACIÓN INICIAL:

1. Cambiar PRINTER_IP por la IP real de tu impresora XP-A160H
2. Verificar que la impresora esté en la misma red
3. Ejecutar: python manage.py collectstatic
4. Crear directorio de logs: mkdir logs (se crea automáticamente)

VERIFICAR IP DE LA IMPRESORA:

1. Imprime una página de configuración desde la impresora
2. O desde el panel de la impresora: Configuración > Red > Información
3. También puedes usar herramientas de red como nmap o arp-scan

PRUEBA DE CONECTIVIDAD:

ping [IP_DE_LA_IMPRESORA]
telnet [IP_DE_LA_IMPRESORA] 9100

ACCESO MÓVIL:

1. Asegúrate de que tu dispositivo móvil esté en la misma red WiFi
2. Usa la IP del servidor: http://[IP_DEL_SERVIDOR]:8000
3. Ejemplo: http://10.201.71.215:8000

PARA PRODUCCIÓN:

1. Cambiar DEBUG = False
2. Configurar SECRET_KEY desde variable de entorno
3. Usar HTTPS y configurar certificados SSL
4. Configurar firewall para permitir solo IPs necesarias
5. Usar base de datos en servidor dedicado
"""