# Generated by Django 5.1.7 on 2025-05-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_pedido_estado_pago"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoOrden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("requiere_mesa", models.BooleanField(default=True)),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Orden",
                "verbose_name_plural": "Tipos de Órdenes",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="nombre_cliente",
            field=models.CharField(
                blank=True,
                help_text="Nombre del cliente para pedidos para llevar",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="numero_orden",
            field=models.CharField(
                blank=True,
                help_text="Número de orden para identificar pedidos para llevar",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="mesa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.mesa",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_orden",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.tipoorden",
            ),
            preserve_default=False,
        ),
    ]
