# Generated by Django 5.1.7 on 2025-07-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_tipoorden_pedido_nombre_cliente_pedido_numero_orden_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pago",
            options={"verbose_name": "Pago", "verbose_name_plural": "Pagos"},
        ),
        migrations.AddField(
            model_name="pago",
            name="costo_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Costo total de los productos vendidos",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="ganancia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ganancia obtenida (total_venta - costo_total)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="total_venta",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total de la venta (igual al monto)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
