# Generated by Django 5.1.7 on 2025-05-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="nombre",
            field=models.CharField(
                choices=[
                    ("administrador", "Administrador"),
                    ("caja", "Caja"),
                    ("cocina", "Cocina"),
                    ("mesero", "Mesero"),
                    ("bar", "Bar"),
                    ("barra", "Barra"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
